### ISSUE TITLE
setNextChannel() called with end channel plus 1

### ISSUE THREAD

**Issue by terrillmoore** [things-nyc/arduino-lmic#15]
Hi @frankleonrose -- nice work.

In merging back to my codebase, I noticed that `setNextChannel()` is called either with `setNextChannel(0, 64, ...)` or `setNextChannel(64, 64+8, ...)`. 

The second parameter is called `end`; this implies it's the last channel. But the calls are coded as "last channel plus 1". Shouldn't these be `setNextChannel(0, 63, ...)` and `setNextChannel(64, 64+8-1, ...)`?  

It looks harmless, provided that the number of enabled channels is less than the count.

**Comment by frankleonrose** [comment]
It's a `[start, end)` range specification, so the calls are correct. How would you prefer that were annotated? `@param` comment?

**Comment by terrillmoore** [comment]
But…  end of the channel range is 63, not 64 (for the 125kHz).  And end of channel range for 500 kHz is 71, not 72.

 

Usually would think it was (base, length) – in which case length is number of channels, or (first, last) where last is last actual channel. As used ssems to be (first, last+1) which is a very unusual API.

 

--Terry

**Comment by frankleonrose** [comment]
Range notation: `[start,` (inclusive) `end)` (exclusive)

**Comment by terrillmoore** [comment]
If that’s the intent, we can close the issue. No big deal, just easy to miss. It’s not a public API so it’s not terribly important.

 

--Terry
