### ISSUE TITLE
better print for received bytes.  

### ISSUE THREAD

**Issue by samlist21** [things-nyc/arduino-lmic#20]
Received bytes currently does this. 
23973025: EV_TXCOMPLETE (includes waiting for RX windows)
Received 
3
 bytes of payload

Change: 
            if (LMIC.dataLen) {
              Serial.println(F("Received "));
              Serial.println(LMIC.dataLen);
              Serial.println(F(" bytes of payload"));

to: 

            if (LMIC.dataLen) {
              Serial.print(F("Received "));
              Serial.print(LMIC.dataLen);
              Serial.println(F(" bytes of payload"));

Then the received byte count will print on the same line.  

Suggest adding the actual received data too.  I'm working on that. Sorry I'm still learning Git or I would fix these and push new code when it is fixed.

**Comment by frankleonrose** [comment]
Thanks, @samlist21. I've made the mod you suggest. Next time, you'll have to learn to fish. :-) (Fork this repo to your account, clone it locally, make your edits, sync changes to your forked repo, then issue a PR from your forked version to this one.) Are you using the GitHub Desktop client? It makes things pretty easy.
